### ISSUE TITLE
QQ: Is 'latest' docker image stable?

### ISSUE THREAD

**Issue by mainiak** [chop-dbhi/prometheus-sql#85]
Hello.

Looking at https://hub.docker.com/r/dbhi/prometheus-sql/tags?page=1&ordering=last_updated
I am not sure if docker image with tag 'latest' is beta / release candidate / or just plain release.

![image](https://user-images.githubusercontent.com/691076/121612874-2bea6080-ca10-11eb-9604-ddf5b05fbfab.png)

Can you please clarify what is intended purpose for 'latest' version from your point of view?

Thank you in advance for your reply.

**Comment by haxorof** [comment]
Hi @mainiak!

I understand you confusion and I do not have insight into how the Docker build is setup on Docker Hub due to access. I assume "latest" currently means "master".

@bruth - Could you make sure the following build rules are configured in Docker Hub for prometheus-sql:

Source Type = `Branch`
Source = `master`
Docker Tag = `master`
Dockerfile location = `Dockerfile`
Build Context = `/`

Source Type = `Tag`
Source = `/^[0-9.]+$/`
Docker Tag = `latest`
Dockerfile location = `Dockerfile`
Build Context = `/`

Source Type = `Tag`
Source = `/^[0-9.]+$/`
Docker Tag = `{sourceref}`
Dockerfile location = `Dockerfile`
Build Context = `/`

Having the above configuration will ensure at least latest tagged build will trigger the build of `latest`. And then `master` will then be latest commit on `master`.

Cheers!

**Comment by bruth** [comment]
I am not sure why Docker Hub was showing that, but this is what I see today.

<img width="1275" alt="Screen Shot 2021-06-22 at 9 26 40 PM" src="https://user-images.githubusercontent.com/515142/123020618-913f3980-d3a0-11eb-8959-20074379d1f7.png">

**Comment by haxorof** [comment]
Hi @bruth,

I did a new bug fix release where quickly fixed two bugs and bumped some version on dependencies, added a changelog also: https://www.github.com/chop-dbhi/prometheus-sql/tree/master/CHANGELOG.md

To make it better around what is built could you check the Docker hub build configuration and maybe set it as I suggested in previous post?

**Comment by bruth** [comment]
@haxorof Updated the automated builds.

<img width="1240" alt="Screen Shot 2021-07-06 at 7 23 30 AM" src="https://user-images.githubusercontent.com/515142/124592096-13ad0c00-de2b-11eb-8449-b0a727ca6039.png">

**Comment by haxorof** [comment]
From now on:
* master tag in Docker hub will be latest commit in Github
* latest tag in Docker hub will be same commit in Github as the latest git tag
* version based tag in Docker hub will be the commit matching the version git tag in Github
